apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-pod
  labels:
    tier: proxy
    part: backend
    type: pod
spec:
  containers:
    - name: nginx-cont
      image: nginx
      ports:
        - containerPort: 80
